# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Package for Release

on: 
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest     

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run build --if-present
      env:
        CI: true
        API_KEY: ${{ secrets.API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOEKN }}
        
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: dist
        path: dist
        
    - name: Zip Files for Release
      uses: papeloto/action-zip@v1
      with:
        files: manifest.json, dist/code.js, dist/ui.js, dist/ui.html
        dest: pexels-figma-plugin.zip
    
    - name: Create Release
      uses: ncipollo/release-action@v1.6.1
      with:
        allowUpdates: true
        artifacts: pexels-figma-plugin.zip
        token: ${{ secrets.GITHUB_TOKEN }}
